[package]
name = "rs-samples"
version = "0.1.0"
edition = "2021"

[dependencies]
ascii = "1.1.0"
lazy_static = "1.4.0"
rand = "0.8.5"
serde = {version = "1.0.147", features = ["derive"] }
serde_json = "1.0.89"
